# frozen_string_literal: true

describe AdventOfCode::Year2024::Day08::Part2 do
  describe "result" do
    subject { described_class.new(data).result }

    let(:data) do
      <<~DATA
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
      DATA
    end

    it { is_expected.to eq 34 }
  end
end
